name: Build Jrebel Server

on:
  push:
    branches:
      - dev
    tags:
      - '*'

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3

      - name: build linux amd64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build-bin/jrebel-license-active-server-linux_amd64 ./
      - name: build linux arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o build-bin/jrebel-license-active-server-linux_arm64 ./
      - name: build mac amd64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o build-bin/jrebel-license-active-server-darwin_amd64 ./
      - name: build mac arm64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o build-bin/jrebel-license-active-server-darwin_arm64 ./
      - name: build windows amd64
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o build-bin/jrebel-license-active-server-windows_amd64.exe ./

      #    - name: Config Linux amd64
      #      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64
      #    - name: Build Linux amd64
      #      run: go build -o build-bin/jrebel-license-active-server-linux_amd64 ./
      #
      #    - name: Config MacOS amd64
      #      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64
      #    - name: Build MacOS amd64
      #      run: go build -o build-bin/jrebel-license-active-server-darwin_amd64 ./
      #
      #    - name: Config Windows amd64
      #      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64
      #    - name: Build Windows amd64
      #      run: go build -o build-bin/jrebel-license-active-server-windows_amd64.exe ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: jrebel-active-server
          path: build-bin/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release artifacts
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-bin/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
